### ISSUE TITLE
SSR issue

### ISSUE THREAD

**Issue by tabvn** [prismicio-community/slice-library-starter-next#4]
Dear Team

i got problem SSR rendering currently all pages can not have html tag durring SSR rendering

i created another test page like 

/pages/test/index.html

```

import React from "react";

const Test = () => {
  return (
    <div>
      <h1>Test</h1>
    </div>
  );
};

export default Test;
```

but when i view source code i can not find h1 tag 

could you please tell me what is happening ?

Best regards,
Toan

**Comment by a-trost** [comment]
Hey @tabvn, I'm unable to reproduce this. When I pasted your code in and viewed source I was able to see the h1.

![image](https://user-images.githubusercontent.com/19617280/116388354-bde43400-a7e9-11eb-8755-dd7678a438bf.png)

If you put your repo somewhere and post to the [Prismic community forums](https://community.prismic.io/) we should be able to get your project running smoothly. Thanks!

**Comment by tabvn** [comment]
hi @a-trost 

i record this screen video 

https://www.loom.com/share/ac48ae03d17d49b3bac25f4bb660fb0d


it seem strange

next.js SSR does not working.
